### ISSUE TITLE
Dynamically adding attributes to dataclass instance

### ISSUE THREAD

**Issue by jacopoabramo** [pyapp-kit/psygnal#328]
### Description

I'm currently working on a project using psygnal where there is heavy utilization of dataclasses. Specifically, I'm using pydantic dataclasses (mostly because I want something simple to be able to load JSON/yaml files in my application and the dataclasses natively do not have type checking functionalities as pydantic does).

As I'm currently in the design stage, I noticed the possibility of usign evented dataclasses and it would be pretty useful to have them. The catch is that I would also like the dataclasses to be dynamically changed during the application startup. It would provide some benefit in what I want to achieve to have more flexibility for users that want to enrich their customization.

### What I Did

I attempted the following

```python
from psygnal import evented
from pydantic.dataclasses import dataclass

@evented
@dataclass
class Example:
    name: str
    age: int

example = Example(name="Alice", age=30)
setattr(example, "profession", "Software Engineer")

@example.events.profession.connect
def on_profession_changed(prof: str):
    print(f"Alice's profession changed to {prof}.")

example.profession = "Medic"
```

But, unsurprisingly, I got the following exception:

```
Traceback (most recent call last):
  File "C:\sandbox\python\sandbox.py", line 16, in <module>
    @example.events.profession.connect
     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jacop\miniforge3\envs\mamba-sandbox\Lib\site-packages\psygnal\_group.py", line 394, in __getattr__
    raise AttributeError(  # pragma: no cover
AttributeError: 'ExampleSignalGroup' object has no attribute 'profession'
```

Now the question is: how hard would it be to have this kind of feature? Or is there an alternative strategy I could deploy?

EDIT: from the documentation the suggested approach would be to explicitly set `SignalGroupDescriptor`. I'm also ok with that approach, but I got the same error anyway.

**Comment by tlambert03** [comment]
oof... yeah.  The key problem here is that that's just not how dataclasses were designed (be they from pydantic or standard lib).  Specifically: all dataclasses have some sort of mechanism to query the fields of the dataclass (such as the ][`dataclasses.fields` function](https://docs.python.org/3/library/dataclasses.html#dataclasses.fields) or the [pydantic `model_fields()`](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_fields) class method.  Because both pydantic and dataclasses are concerned with type-annotated fields, they specifically don't pay any attention to dynamically added instance attributes like the one you're adding here:

```python
In [1]: from pydantic.dataclasses import dataclass

In [2]: from dataclasses import fields

In [3]: @dataclass
   ...: class Example:
   ...:     name: str
   ...:     age: int
   ...:

In [4]: fields(Example)
Out[4]:

(
    Field(name='name',type=<class 'str'>,default=<dataclasses._MISSING_TYPE object at 0x103408bd0>,default_factory=<dataclasses._MISSING_TYPE object at 0x103408bd0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD),
    Field(name='age',type=<class 'int'>,default=<dataclasses._MISSING_TYPE object at 0x103408bd0>,default_factory=<dataclasses._MISSING_TYPE object at 0x103408bd0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD)
)

In [5]: example = Example(name="Alice", age=30)
   ...: setattr(example, "profession", "Software Engineer")

# doesn't change anything
In [6]: fields(example)
Out[6]:

(
    Field(name='name',type=<class 'str'>,default=<dataclasses._MISSING_TYPE object at 0x103408bd0>,default_factory=<dataclasses._MISSING_TYPE object at 0x103408bd0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD),
    Field(name='age',type=<class 'int'>,default=<dataclasses._MISSING_TYPE object at 0x103408bd0>,default_factory=<dataclasses._MISSING_TYPE object at 0x103408bd0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD)
)
```

If you must dynamically add attributes, but you also want them to be proper fields on a dataclass or pydantic model, then your best bet is probably to instantiate a dynamically constructed *class*, rather than dynamically adding attributes to a pre-existing instance:

```python
from psygnal import evented
from pydantic.dataclasses import dataclass


@dataclass
class Example:
    name: str
    age: int

# dynamically creating a subclass with a new field
DynamicExample = type(
    "DynamicExample",
    (Example,),
    {"__annotations__": {"profession": str}, "profession": ""},
)

DynamicExample = evented(dataclass(DynamicExample))
example = DynamicExample(name="Alice", age=30)


@example.events.profession.connect
def on_profession_changed(prof: str):
    print(f"Alice's profession changed to {prof}.")


example.profession = "Medic"
```

if the dynamic subclass option is still unsuitable for some reason, then I think your only option is some super deep magic (which I would definitely not encourage), that would inevitably dig pretty deep into the mechanics of the specific dataclass-like solution you're using (so, it would be different for pydantic vs stdlib dataclasses).  I started to create an example for you, but it got so gross that I stopped :). basically, don't do it: fields on dataclasses and pydantic models are pretty strictly defined on the class, not on the instance

**Comment by tlambert03** [comment]
> EDIT: from the documentation the suggested approach would be to explicitly set SignalGroupDescriptor. I'm also ok with that approach, but I got the same error anyway.

this really wouldn't get you what you're after.  if you're using pydantic because you like serialization and/or validation mechanisms, then those still won't work for your dynamically added fields.  All of these tools just aren't designed for this sort of dynamic instance modification

**Comment by jacopoabramo** [comment]
> I started to create an example for you, but it got so gross that I stopped :)

Ahah, I feel you!

Thank you for the quick response anyway. Actually the approach of using a dynamically typed class might be what I need to make it work, so I will test that approach. Closing, thanks again!
